name: Deploy DV Lottery Image Bot to Aeza Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    environment:
      name: "Production"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log in to Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: aliir74
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          push: true
          tags: aliir74/dv-lottery-image-bot:latest
          file: ./Dockerfile
          cache-from: type=registry,ref=aliir74/dv-lottery-image-bot:latest
          cache-to: type=inline

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"

    steps:
      - name: Deploy to aeza server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker system prune -f --all
            docker pull aliir74/dv-lottery-image-bot:latest
            if [ ! -d "dv-lottery-image-bot" ]; then
                mkdir dv-lottery-image-bot
            fi
            cd dv-lottery-image-bot
            touch .env
            echo "${{ vars.ENVS }}" > .env
            echo "${{ secrets.ENVS }}" >> .env
            docker stop dv-lottery-image-bot
            docker rm dv-lottery-image-bot
            docker run -d \
              -v ~/dv-lottery-image-bot/database:/app/database \
              -v ~/dv-lottery-image-bot/images:/app/images \
              --restart always \
              --env-file .env \
              --name dv-lottery-image-bot \
              aliir74/dv-lottery-image-bot:latest
